return require 'parse.char.utf8.set.Letter.Lowercase'
	+ require 'parse.char.utf8.set.Letter.Uppercase'
	+ require 'parse.char.utf8.set.Letter.Titlecase'
	+ require 'parse.char.utf8.set.Letter.Modifier'
	+ require 'parse.char.utf8.set.Letter.Other'
