
local byte = require 'parse.substitution.charset.byte'

return byte + {
	['\xa1'] = require 'parse.substitution.undefined_char';
	['\xa2'] = require 'parse.substitution.undefined_char';
	['\xa3'] = require 'parse.substitution.undefined_char';
	['\xa5'] = require 'parse.substitution.undefined_char';
	['\xa6'] = require 'parse.substitution.undefined_char';
	['\xa7'] = require 'parse.substitution.undefined_char';
	['\xa8'] = require 'parse.substitution.undefined_char';
	['\xa9'] = require 'parse.substitution.undefined_char';
	['\xaa'] = require 'parse.substitution.undefined_char';
	['\xab'] = require 'parse.substitution.undefined_char';
	['\xac'] = '\u{60c}'; -- arabic comma
	['\xae'] = require 'parse.substitution.undefined_char';
	['\xaf'] = require 'parse.substitution.undefined_char';
	['\xb0'] = require 'parse.substitution.undefined_char';
	['\xb1'] = require 'parse.substitution.undefined_char';
	['\xb2'] = require 'parse.substitution.undefined_char';
	['\xb3'] = require 'parse.substitution.undefined_char';
	['\xb4'] = require 'parse.substitution.undefined_char';
	['\xb5'] = require 'parse.substitution.undefined_char';
	['\xb6'] = require 'parse.substitution.undefined_char';
	['\xb7'] = require 'parse.substitution.undefined_char';
	['\xb8'] = require 'parse.substitution.undefined_char';
	['\xb9'] = require 'parse.substitution.undefined_char';
	['\xba'] = require 'parse.substitution.undefined_char';
	['\xbb'] = '\u{61b}'; -- arabic semicolon
	['\xbc'] = require 'parse.substitution.undefined_char';
	['\xbd'] = require 'parse.substitution.undefined_char';
	['\xbe'] = require 'parse.substitution.undefined_char';
	['\xbf'] = '\u{61f}'; -- arabic question mark
	['\xc0'] = require 'parse.substitution.undefined_char';
	['\xc1'] = '\u{621}'; -- arabic letter hamza
	['\xc2'] = '\u{622}'; -- arabic letter alef with madda above
	['\xc3'] = '\u{623}'; -- arabic letter alef with hamza above
	['\xc4'] = '\u{624}'; -- arabic letter waw with hamza above
	['\xc5'] = '\u{625}'; -- arabic letter alef with hamza below
	['\xc6'] = '\u{626}'; -- arabic letter yeh with hamza above
	['\xc7'] = '\u{627}'; -- arabic letter alef
	['\xc8'] = '\u{628}'; -- arabic letter beh
	['\xc9'] = '\u{629}'; -- arabic letter teh marbuta
	['\xca'] = '\u{62a}'; -- arabic letter teh
	['\xcb'] = '\u{62b}'; -- arabic letter theh
	['\xcc'] = '\u{62c}'; -- arabic letter jeem
	['\xcd'] = '\u{62d}'; -- arabic letter hah
	['\xce'] = '\u{62e}'; -- arabic letter khah
	['\xcf'] = '\u{62f}'; -- arabic letter dal
	['\xd0'] = '\u{630}'; -- arabic letter thal
	['\xd1'] = '\u{631}'; -- arabic letter reh
	['\xd2'] = '\u{632}'; -- arabic letter zain
	['\xd3'] = '\u{633}'; -- arabic letter seen
	['\xd4'] = '\u{634}'; -- arabic letter sheen
	['\xd5'] = '\u{635}'; -- arabic letter sad
	['\xd6'] = '\u{636}'; -- arabic letter dad
	['\xd7'] = '\u{637}'; -- arabic letter tah
	['\xd8'] = '\u{638}'; -- arabic letter zah
	['\xd9'] = '\u{639}'; -- arabic letter ain
	['\xda'] = '\u{63a}'; -- arabic letter ghain
	['\xdb'] = require 'parse.substitution.undefined_char';
	['\xdc'] = require 'parse.substitution.undefined_char';
	['\xdd'] = require 'parse.substitution.undefined_char';
	['\xde'] = require 'parse.substitution.undefined_char';
	['\xdf'] = require 'parse.substitution.undefined_char';
	['\xe0'] = '\u{640}'; -- arabic tatweel
	['\xe1'] = '\u{641}'; -- arabic letter feh
	['\xe2'] = '\u{642}'; -- arabic letter qaf
	['\xe3'] = '\u{643}'; -- arabic letter kaf
	['\xe4'] = '\u{644}'; -- arabic letter lam
	['\xe5'] = '\u{645}'; -- arabic letter meem
	['\xe6'] = '\u{646}'; -- arabic letter noon
	['\xe7'] = '\u{647}'; -- arabic letter heh
	['\xe8'] = '\u{648}'; -- arabic letter waw
	['\xe9'] = '\u{649}'; -- arabic letter alef maksura
	['\xea'] = '\u{64a}'; -- arabic letter yeh
	['\xeb'] = '\u{64b}'; -- arabic fathatan
	['\xec'] = '\u{64c}'; -- arabic dammatan
	['\xed'] = '\u{64d}'; -- arabic kasratan
	['\xee'] = '\u{64e}'; -- arabic fatha
	['\xef'] = '\u{64f}'; -- arabic damma
	['\xf0'] = '\u{650}'; -- arabic kasra
	['\xf1'] = '\u{651}'; -- arabic shadda
	['\xf2'] = '\u{652}'; -- arabic sukun
	['\xf3'] = require 'parse.substitution.undefined_char';
	['\xf4'] = require 'parse.substitution.undefined_char';
	['\xf5'] = require 'parse.substitution.undefined_char';
	['\xf6'] = require 'parse.substitution.undefined_char';
	['\xf7'] = require 'parse.substitution.undefined_char';
	['\xf8'] = require 'parse.substitution.undefined_char';
	['\xf9'] = require 'parse.substitution.undefined_char';
	['\xfa'] = require 'parse.substitution.undefined_char';
	['\xfb'] = require 'parse.substitution.undefined_char';
	['\xfc'] = require 'parse.substitution.undefined_char';
	['\xfd'] = require 'parse.substitution.undefined_char';
	['\xfe'] = require 'parse.substitution.undefined_char';
	['\xff'] = require 'parse.substitution.undefined_char';
}
