
local byte = require 'parse.substitution.charset.byte'

return byte + {
	['\xa1'] = '\u{2018}'; -- left single quotation mark
	['\xa2'] = '\u{2019}'; -- right single quotation mark
	['\xa4'] = '\u{20ac}'; -- euro sign
	['\xa5'] = '\u{20af}'; -- drachma sign
	['\xaa'] = '\u{37a}'; -- greek ypogegrammeni
	['\xae'] = require 'parse.substitution.undefined_char';
	['\xaf'] = '\u{2015}'; -- horizontal bar
	['\xb4'] = '\u{384}'; -- greek tonos
	['\xb5'] = '\u{385}'; -- greek dialytika tonos
	['\xb6'] = '\u{386}'; -- greek capital letter alpha with tonos
	['\xb8'] = '\u{388}'; -- greek capital letter epsilon with tonos
	['\xb9'] = '\u{389}'; -- greek capital letter eta with tonos
	['\xba'] = '\u{38a}'; -- greek capital letter iota with tonos
	['\xbc'] = '\u{38c}'; -- greek capital letter omicron with tonos
	['\xbe'] = '\u{38e}'; -- greek capital letter upsilon with tonos
	['\xbf'] = '\u{38f}'; -- greek capital letter omega with tonos
	['\xc0'] = '\u{390}'; -- greek small letter iota with dialytika and tonos
	['\xc1'] = '\u{391}'; -- greek capital letter alpha
	['\xc2'] = '\u{392}'; -- greek capital letter beta
	['\xc3'] = '\u{393}'; -- greek capital letter gamma
	['\xc4'] = '\u{394}'; -- greek capital letter delta
	['\xc5'] = '\u{395}'; -- greek capital letter epsilon
	['\xc6'] = '\u{396}'; -- greek capital letter zeta
	['\xc7'] = '\u{397}'; -- greek capital letter eta
	['\xc8'] = '\u{398}'; -- greek capital letter theta
	['\xc9'] = '\u{399}'; -- greek capital letter iota
	['\xca'] = '\u{39a}'; -- greek capital letter kappa
	['\xcb'] = '\u{39b}'; -- greek capital letter lamda
	['\xcc'] = '\u{39c}'; -- greek capital letter mu
	['\xcd'] = '\u{39d}'; -- greek capital letter nu
	['\xce'] = '\u{39e}'; -- greek capital letter xi
	['\xcf'] = '\u{39f}'; -- greek capital letter omicron
	['\xd0'] = '\u{3a0}'; -- greek capital letter pi
	['\xd1'] = '\u{3a1}'; -- greek capital letter rho
	['\xd2'] = require 'parse.substitution.undefined_char';
	['\xd3'] = '\u{3a3}'; -- greek capital letter sigma
	['\xd4'] = '\u{3a4}'; -- greek capital letter tau
	['\xd5'] = '\u{3a5}'; -- greek capital letter upsilon
	['\xd6'] = '\u{3a6}'; -- greek capital letter phi
	['\xd7'] = '\u{3a7}'; -- greek capital letter chi
	['\xd8'] = '\u{3a8}'; -- greek capital letter psi
	['\xd9'] = '\u{3a9}'; -- greek capital letter omega
	['\xda'] = '\u{3aa}'; -- greek capital letter iota with dialytika
	['\xdb'] = '\u{3ab}'; -- greek capital letter upsilon with dialytika
	['\xdc'] = '\u{3ac}'; -- greek small letter alpha with tonos
	['\xdd'] = '\u{3ad}'; -- greek small letter epsilon with tonos
	['\xde'] = '\u{3ae}'; -- greek small letter eta with tonos
	['\xdf'] = '\u{3af}'; -- greek small letter iota with tonos
	['\xe0'] = '\u{3b0}'; -- greek small letter upsilon with dialytika and tonos
	['\xe1'] = '\u{3b1}'; -- greek small letter alpha
	['\xe2'] = '\u{3b2}'; -- greek small letter beta
	['\xe3'] = '\u{3b3}'; -- greek small letter gamma
	['\xe4'] = '\u{3b4}'; -- greek small letter delta
	['\xe5'] = '\u{3b5}'; -- greek small letter epsilon
	['\xe6'] = '\u{3b6}'; -- greek small letter zeta
	['\xe7'] = '\u{3b7}'; -- greek small letter eta
	['\xe8'] = '\u{3b8}'; -- greek small letter theta
	['\xe9'] = '\u{3b9}'; -- greek small letter iota
	['\xea'] = '\u{3ba}'; -- greek small letter kappa
	['\xeb'] = '\u{3bb}'; -- greek small letter lamda
	['\xec'] = '\u{3bc}'; -- greek small letter mu
	['\xed'] = '\u{3bd}'; -- greek small letter nu
	['\xee'] = '\u{3be}'; -- greek small letter xi
	['\xef'] = '\u{3bf}'; -- greek small letter omicron
	['\xf0'] = '\u{3c0}'; -- greek small letter pi
	['\xf1'] = '\u{3c1}'; -- greek small letter rho
	['\xf2'] = '\u{3c2}'; -- greek small letter final sigma
	['\xf3'] = '\u{3c3}'; -- greek small letter sigma
	['\xf4'] = '\u{3c4}'; -- greek small letter tau
	['\xf5'] = '\u{3c5}'; -- greek small letter upsilon
	['\xf6'] = '\u{3c6}'; -- greek small letter phi
	['\xf7'] = '\u{3c7}'; -- greek small letter chi
	['\xf8'] = '\u{3c8}'; -- greek small letter psi
	['\xf9'] = '\u{3c9}'; -- greek small letter omega
	['\xfa'] = '\u{3ca}'; -- greek small letter iota with dialytika
	['\xfb'] = '\u{3cb}'; -- greek small letter upsilon with dialytika
	['\xfc'] = '\u{3cc}'; -- greek small letter omicron with tonos
	['\xfd'] = '\u{3cd}'; -- greek small letter upsilon with tonos
	['\xfe'] = '\u{3ce}'; -- greek small letter omega with tonos
	['\xff'] = require 'parse.substitution.undefined_char';
}
