
local byte = require 'parse.substitution.charset.byte'

return byte + {
	['\x80'] = '\u{402}'; -- cyrillic capital letter dje
	['\x81'] = '\u{403}'; -- cyrillic capital letter gje
	['\x82'] = '\u{201a}'; -- single low-9 quotation mark
	['\x83'] = '\u{453}'; -- cyrillic small letter gje
	['\x84'] = '\u{201e}'; -- double low-9 quotation mark
	['\x85'] = '\u{2026}'; -- horizontal ellipsis
	['\x86'] = '\u{2020}'; -- dagger
	['\x87'] = '\u{2021}'; -- double dagger
	['\x88'] = '\u{20ac}'; -- euro sign
	['\x89'] = '\u{2030}'; -- per mille sign
	['\x8a'] = '\u{409}'; -- cyrillic capital letter lje
	['\x8b'] = '\u{2039}'; -- single left-pointing angle quotation mark
	['\x8c'] = '\u{40a}'; -- cyrillic capital letter nje
	['\x8d'] = '\u{40c}'; -- cyrillic capital letter kje
	['\x8e'] = '\u{40b}'; -- cyrillic capital letter tshe
	['\x8f'] = '\u{40f}'; -- cyrillic capital letter dzhe
	['\x90'] = '\u{452}'; -- cyrillic small letter dje
	['\x91'] = '\u{2018}'; -- left single quotation mark
	['\x92'] = '\u{2019}'; -- right single quotation mark
	['\x93'] = '\u{201c}'; -- left double quotation mark
	['\x94'] = '\u{201d}'; -- right double quotation mark
	['\x95'] = '\u{2022}'; -- bullet
	['\x96'] = '\u{2013}'; -- en dash
	['\x97'] = '\u{2014}'; -- em dash
	['\x98'] = require 'parse.substitution.undefined_char';
	['\x99'] = '\u{2122}'; -- trade mark sign
	['\x9a'] = '\u{459}'; -- cyrillic small letter lje
	['\x9b'] = '\u{203a}'; -- single right-pointing angle quotation mark
	['\x9c'] = '\u{45a}'; -- cyrillic small letter nje
	['\x9d'] = '\u{45c}'; -- cyrillic small letter kje
	['\x9e'] = '\u{45b}'; -- cyrillic small letter tshe
	['\x9f'] = '\u{45f}'; -- cyrillic small letter dzhe
	['\xa1'] = '\u{40e}'; -- cyrillic capital letter short u
	['\xa2'] = '\u{45e}'; -- cyrillic small letter short u
	['\xa3'] = '\u{408}'; -- cyrillic capital letter je
	['\xa5'] = '\u{490}'; -- cyrillic capital letter ghe with upturn
	['\xa8'] = '\u{401}'; -- cyrillic capital letter io
	['\xaa'] = '\u{404}'; -- cyrillic capital letter ukrainian ie
	['\xaf'] = '\u{407}'; -- cyrillic capital letter yi
	['\xb2'] = '\u{406}'; -- cyrillic capital letter byelorussian-ukrainian i
	['\xb3'] = '\u{456}'; -- cyrillic small letter byelorussian-ukrainian i
	['\xb4'] = '\u{491}'; -- cyrillic small letter ghe with upturn
	['\xb8'] = '\u{451}'; -- cyrillic small letter io
	['\xb9'] = '\u{2116}'; -- numero sign
	['\xba'] = '\u{454}'; -- cyrillic small letter ukrainian ie
	['\xbc'] = '\u{458}'; -- cyrillic small letter je
	['\xbd'] = '\u{405}'; -- cyrillic capital letter dze
	['\xbe'] = '\u{455}'; -- cyrillic small letter dze
	['\xbf'] = '\u{457}'; -- cyrillic small letter yi
	['\xc0'] = '\u{410}'; -- cyrillic capital letter a
	['\xc1'] = '\u{411}'; -- cyrillic capital letter be
	['\xc2'] = '\u{412}'; -- cyrillic capital letter ve
	['\xc3'] = '\u{413}'; -- cyrillic capital letter ghe
	['\xc4'] = '\u{414}'; -- cyrillic capital letter de
	['\xc5'] = '\u{415}'; -- cyrillic capital letter ie
	['\xc6'] = '\u{416}'; -- cyrillic capital letter zhe
	['\xc7'] = '\u{417}'; -- cyrillic capital letter ze
	['\xc8'] = '\u{418}'; -- cyrillic capital letter i
	['\xc9'] = '\u{419}'; -- cyrillic capital letter short i
	['\xca'] = '\u{41a}'; -- cyrillic capital letter ka
	['\xcb'] = '\u{41b}'; -- cyrillic capital letter el
	['\xcc'] = '\u{41c}'; -- cyrillic capital letter em
	['\xcd'] = '\u{41d}'; -- cyrillic capital letter en
	['\xce'] = '\u{41e}'; -- cyrillic capital letter o
	['\xcf'] = '\u{41f}'; -- cyrillic capital letter pe
	['\xd0'] = '\u{420}'; -- cyrillic capital letter er
	['\xd1'] = '\u{421}'; -- cyrillic capital letter es
	['\xd2'] = '\u{422}'; -- cyrillic capital letter te
	['\xd3'] = '\u{423}'; -- cyrillic capital letter u
	['\xd4'] = '\u{424}'; -- cyrillic capital letter ef
	['\xd5'] = '\u{425}'; -- cyrillic capital letter ha
	['\xd6'] = '\u{426}'; -- cyrillic capital letter tse
	['\xd7'] = '\u{427}'; -- cyrillic capital letter che
	['\xd8'] = '\u{428}'; -- cyrillic capital letter sha
	['\xd9'] = '\u{429}'; -- cyrillic capital letter shcha
	['\xda'] = '\u{42a}'; -- cyrillic capital letter hard sign
	['\xdb'] = '\u{42b}'; -- cyrillic capital letter yeru
	['\xdc'] = '\u{42c}'; -- cyrillic capital letter soft sign
	['\xdd'] = '\u{42d}'; -- cyrillic capital letter e
	['\xde'] = '\u{42e}'; -- cyrillic capital letter yu
	['\xdf'] = '\u{42f}'; -- cyrillic capital letter ya
	['\xe0'] = '\u{430}'; -- cyrillic small letter a
	['\xe1'] = '\u{431}'; -- cyrillic small letter be
	['\xe2'] = '\u{432}'; -- cyrillic small letter ve
	['\xe3'] = '\u{433}'; -- cyrillic small letter ghe
	['\xe4'] = '\u{434}'; -- cyrillic small letter de
	['\xe5'] = '\u{435}'; -- cyrillic small letter ie
	['\xe6'] = '\u{436}'; -- cyrillic small letter zhe
	['\xe7'] = '\u{437}'; -- cyrillic small letter ze
	['\xe8'] = '\u{438}'; -- cyrillic small letter i
	['\xe9'] = '\u{439}'; -- cyrillic small letter short i
	['\xea'] = '\u{43a}'; -- cyrillic small letter ka
	['\xeb'] = '\u{43b}'; -- cyrillic small letter el
	['\xec'] = '\u{43c}'; -- cyrillic small letter em
	['\xed'] = '\u{43d}'; -- cyrillic small letter en
	['\xee'] = '\u{43e}'; -- cyrillic small letter o
	['\xef'] = '\u{43f}'; -- cyrillic small letter pe
	['\xf0'] = '\u{440}'; -- cyrillic small letter er
	['\xf1'] = '\u{441}'; -- cyrillic small letter es
	['\xf2'] = '\u{442}'; -- cyrillic small letter te
	['\xf3'] = '\u{443}'; -- cyrillic small letter u
	['\xf4'] = '\u{444}'; -- cyrillic small letter ef
	['\xf5'] = '\u{445}'; -- cyrillic small letter ha
	['\xf6'] = '\u{446}'; -- cyrillic small letter tse
	['\xf7'] = '\u{447}'; -- cyrillic small letter che
	['\xf8'] = '\u{448}'; -- cyrillic small letter sha
	['\xf9'] = '\u{449}'; -- cyrillic small letter shcha
	['\xfa'] = '\u{44a}'; -- cyrillic small letter hard sign
	['\xfb'] = '\u{44b}'; -- cyrillic small letter yeru
	['\xfc'] = '\u{44c}'; -- cyrillic small letter soft sign
	['\xfd'] = '\u{44d}'; -- cyrillic small letter e
	['\xfe'] = '\u{44e}'; -- cyrillic small letter yu
	['\xff'] = '\u{44f}'; -- cyrillic small letter ya
}
