
local byte = require 'parse.substitution.charset.byte'

return byte + {
	['\x80'] = '\u{20ac}'; -- euro sign
	['\x81'] = '\u{67e}'; -- arabic letter peh
	['\x82'] = '\u{201a}'; -- single low-9 quotation mark
	['\x83'] = '\u{192}'; -- latin small letter f with hook
	['\x84'] = '\u{201e}'; -- double low-9 quotation mark
	['\x85'] = '\u{2026}'; -- horizontal ellipsis
	['\x86'] = '\u{2020}'; -- dagger
	['\x87'] = '\u{2021}'; -- double dagger
	['\x88'] = '\u{2c6}'; -- modifier letter circumflex accent
	['\x89'] = '\u{2030}'; -- per mille sign
	['\x8a'] = '\u{679}'; -- arabic letter tteh
	['\x8b'] = '\u{2039}'; -- single left-pointing angle quotation mark
	['\x8c'] = '\u{152}'; -- latin capital ligature oe
	['\x8d'] = '\u{686}'; -- arabic letter tcheh
	['\x8e'] = '\u{698}'; -- arabic letter jeh
	['\x8f'] = '\u{688}'; -- arabic letter ddal
	['\x90'] = '\u{6af}'; -- arabic letter gaf
	['\x91'] = '\u{2018}'; -- left single quotation mark
	['\x92'] = '\u{2019}'; -- right single quotation mark
	['\x93'] = '\u{201c}'; -- left double quotation mark
	['\x94'] = '\u{201d}'; -- right double quotation mark
	['\x95'] = '\u{2022}'; -- bullet
	['\x96'] = '\u{2013}'; -- en dash
	['\x97'] = '\u{2014}'; -- em dash
	['\x98'] = '\u{6a9}'; -- arabic letter keheh
	['\x99'] = '\u{2122}'; -- trade mark sign
	['\x9a'] = '\u{691}'; -- arabic letter rreh
	['\x9b'] = '\u{203a}'; -- single right-pointing angle quotation mark
	['\x9c'] = '\u{153}'; -- latin small ligature oe
	['\x9d'] = '\u{200c}'; -- zero width non-joiner
	['\x9e'] = '\u{200d}'; -- zero width joiner
	['\x9f'] = '\u{6ba}'; -- arabic letter noon ghunna
	['\xa1'] = '\u{60c}'; -- arabic comma
	['\xaa'] = '\u{6be}'; -- arabic letter heh doachashmee
	['\xba'] = '\u{61b}'; -- arabic semicolon
	['\xbf'] = '\u{61f}'; -- arabic question mark
	['\xc0'] = '\u{6c1}'; -- arabic letter heh goal
	['\xc1'] = '\u{621}'; -- arabic letter hamza
	['\xc2'] = '\u{622}'; -- arabic letter alef with madda above
	['\xc3'] = '\u{623}'; -- arabic letter alef with hamza above
	['\xc4'] = '\u{624}'; -- arabic letter waw with hamza above
	['\xc5'] = '\u{625}'; -- arabic letter alef with hamza below
	['\xc6'] = '\u{626}'; -- arabic letter yeh with hamza above
	['\xc7'] = '\u{627}'; -- arabic letter alef
	['\xc8'] = '\u{628}'; -- arabic letter beh
	['\xc9'] = '\u{629}'; -- arabic letter teh marbuta
	['\xca'] = '\u{62a}'; -- arabic letter teh
	['\xcb'] = '\u{62b}'; -- arabic letter theh
	['\xcc'] = '\u{62c}'; -- arabic letter jeem
	['\xcd'] = '\u{62d}'; -- arabic letter hah
	['\xce'] = '\u{62e}'; -- arabic letter khah
	['\xcf'] = '\u{62f}'; -- arabic letter dal
	['\xd0'] = '\u{630}'; -- arabic letter thal
	['\xd1'] = '\u{631}'; -- arabic letter reh
	['\xd2'] = '\u{632}'; -- arabic letter zain
	['\xd3'] = '\u{633}'; -- arabic letter seen
	['\xd4'] = '\u{634}'; -- arabic letter sheen
	['\xd5'] = '\u{635}'; -- arabic letter sad
	['\xd6'] = '\u{636}'; -- arabic letter dad
	['\xd8'] = '\u{637}'; -- arabic letter tah
	['\xd9'] = '\u{638}'; -- arabic letter zah
	['\xda'] = '\u{639}'; -- arabic letter ain
	['\xdb'] = '\u{63a}'; -- arabic letter ghain
	['\xdc'] = '\u{640}'; -- arabic tatweel
	['\xdd'] = '\u{641}'; -- arabic letter feh
	['\xde'] = '\u{642}'; -- arabic letter qaf
	['\xdf'] = '\u{643}'; -- arabic letter kaf
	['\xe1'] = '\u{644}'; -- arabic letter lam
	['\xe3'] = '\u{645}'; -- arabic letter meem
	['\xe4'] = '\u{646}'; -- arabic letter noon
	['\xe5'] = '\u{647}'; -- arabic letter heh
	['\xe6'] = '\u{648}'; -- arabic letter waw
	['\xec'] = '\u{649}'; -- arabic letter alef maksura
	['\xed'] = '\u{64a}'; -- arabic letter yeh
	['\xf0'] = '\u{64b}'; -- arabic fathatan
	['\xf1'] = '\u{64c}'; -- arabic dammatan
	['\xf2'] = '\u{64d}'; -- arabic kasratan
	['\xf3'] = '\u{64e}'; -- arabic fatha
	['\xf5'] = '\u{64f}'; -- arabic damma
	['\xf6'] = '\u{650}'; -- arabic kasra
	['\xf8'] = '\u{651}'; -- arabic shadda
	['\xfa'] = '\u{652}'; -- arabic sukun
	['\xfd'] = '\u{200e}'; -- left-to-right mark
	['\xfe'] = '\u{200f}'; -- right-to-left mark
	['\xff'] = '\u{6d2}'; -- arabic letter yeh barree
}
