
local byte = require 'parse.substitution.charset.byte'

return byte + {
	['\xa1'] = '\u{104}'; -- latin capital letter a with ogonek
	['\xa2'] = '\u{2d8}'; -- breve
	['\xa3'] = '\u{141}'; -- latin capital letter l with stroke
	['\xa5'] = '\u{13d}'; -- latin capital letter l with caron
	['\xa6'] = '\u{15a}'; -- latin capital letter s with acute
	['\xa9'] = '\u{160}'; -- latin capital letter s with caron
	['\xaa'] = '\u{15e}'; -- latin capital letter s with cedilla
	['\xab'] = '\u{164}'; -- latin capital letter t with caron
	['\xac'] = '\u{179}'; -- latin capital letter z with acute
	['\xae'] = '\u{17d}'; -- latin capital letter z with caron
	['\xaf'] = '\u{17b}'; -- latin capital letter z with dot above
	['\xb1'] = '\u{105}'; -- latin small letter a with ogonek
	['\xb2'] = '\u{2db}'; -- ogonek
	['\xb3'] = '\u{142}'; -- latin small letter l with stroke
	['\xb5'] = '\u{13e}'; -- latin small letter l with caron
	['\xb6'] = '\u{15b}'; -- latin small letter s with acute
	['\xb7'] = '\u{2c7}'; -- caron
	['\xb9'] = '\u{161}'; -- latin small letter s with caron
	['\xba'] = '\u{15f}'; -- latin small letter s with cedilla
	['\xbb'] = '\u{165}'; -- latin small letter t with caron
	['\xbc'] = '\u{17a}'; -- latin small letter z with acute
	['\xbd'] = '\u{2dd}'; -- double acute accent
	['\xbe'] = '\u{17e}'; -- latin small letter z with caron
	['\xbf'] = '\u{17c}'; -- latin small letter z with dot above
	['\xc0'] = '\u{154}'; -- latin capital letter r with acute
	['\xc3'] = '\u{102}'; -- latin capital letter a with breve
	['\xc5'] = '\u{139}'; -- latin capital letter l with acute
	['\xc6'] = '\u{106}'; -- latin capital letter c with acute
	['\xc8'] = '\u{10c}'; -- latin capital letter c with caron
	['\xca'] = '\u{118}'; -- latin capital letter e with ogonek
	['\xcc'] = '\u{11a}'; -- latin capital letter e with caron
	['\xcf'] = '\u{10e}'; -- latin capital letter d with caron
	['\xd0'] = '\u{110}'; -- latin capital letter d with stroke
	['\xd1'] = '\u{143}'; -- latin capital letter n with acute
	['\xd2'] = '\u{147}'; -- latin capital letter n with caron
	['\xd5'] = '\u{150}'; -- latin capital letter o with double acute
	['\xd8'] = '\u{158}'; -- latin capital letter r with caron
	['\xd9'] = '\u{16e}'; -- latin capital letter u with ring above
	['\xdb'] = '\u{170}'; -- latin capital letter u with double acute
	['\xde'] = '\u{162}'; -- latin capital letter t with cedilla
	['\xe0'] = '\u{155}'; -- latin small letter r with acute
	['\xe3'] = '\u{103}'; -- latin small letter a with breve
	['\xe5'] = '\u{13a}'; -- latin small letter l with acute
	['\xe6'] = '\u{107}'; -- latin small letter c with acute
	['\xe8'] = '\u{10d}'; -- latin small letter c with caron
	['\xea'] = '\u{119}'; -- latin small letter e with ogonek
	['\xec'] = '\u{11b}'; -- latin small letter e with caron
	['\xef'] = '\u{10f}'; -- latin small letter d with caron
	['\xf0'] = '\u{111}'; -- latin small letter d with stroke
	['\xf1'] = '\u{144}'; -- latin small letter n with acute
	['\xf2'] = '\u{148}'; -- latin small letter n with caron
	['\xf5'] = '\u{151}'; -- latin small letter o with double acute
	['\xf8'] = '\u{159}'; -- latin small letter r with caron
	['\xf9'] = '\u{16f}'; -- latin small letter u with ring above
	['\xfb'] = '\u{171}'; -- latin small letter u with double acute
	['\xfe'] = '\u{163}'; -- latin small letter t with cedilla
	['\xff'] = '\u{2d9}'; -- dot above
}
