
local byte = require 'parse.substitution.charset.byte'

return byte + {
	['\xa1'] = '\u{e01}'; -- thai character ko kai
	['\xa2'] = '\u{e02}'; -- thai character kho khai
	['\xa3'] = '\u{e03}'; -- thai character kho khuat
	['\xa4'] = '\u{e04}'; -- thai character kho khwai
	['\xa5'] = '\u{e05}'; -- thai character kho khon
	['\xa6'] = '\u{e06}'; -- thai character kho rakhang
	['\xa7'] = '\u{e07}'; -- thai character ngo ngu
	['\xa8'] = '\u{e08}'; -- thai character cho chan
	['\xa9'] = '\u{e09}'; -- thai character cho ching
	['\xaa'] = '\u{e0a}'; -- thai character cho chang
	['\xab'] = '\u{e0b}'; -- thai character so so
	['\xac'] = '\u{e0c}'; -- thai character cho choe
	['\xad'] = '\u{e0d}'; -- thai character yo ying
	['\xae'] = '\u{e0e}'; -- thai character do chada
	['\xaf'] = '\u{e0f}'; -- thai character to patak
	['\xb0'] = '\u{e10}'; -- thai character tho than
	['\xb1'] = '\u{e11}'; -- thai character tho nangmontho
	['\xb2'] = '\u{e12}'; -- thai character tho phuthao
	['\xb3'] = '\u{e13}'; -- thai character no nen
	['\xb4'] = '\u{e14}'; -- thai character do dek
	['\xb5'] = '\u{e15}'; -- thai character to tao
	['\xb6'] = '\u{e16}'; -- thai character tho thung
	['\xb7'] = '\u{e17}'; -- thai character tho thahan
	['\xb8'] = '\u{e18}'; -- thai character tho thong
	['\xb9'] = '\u{e19}'; -- thai character no nu
	['\xba'] = '\u{e1a}'; -- thai character bo baimai
	['\xbb'] = '\u{e1b}'; -- thai character po pla
	['\xbc'] = '\u{e1c}'; -- thai character pho phung
	['\xbd'] = '\u{e1d}'; -- thai character fo fa
	['\xbe'] = '\u{e1e}'; -- thai character pho phan
	['\xbf'] = '\u{e1f}'; -- thai character fo fan
	['\xc0'] = '\u{e20}'; -- thai character pho samphao
	['\xc1'] = '\u{e21}'; -- thai character mo ma
	['\xc2'] = '\u{e22}'; -- thai character yo yak
	['\xc3'] = '\u{e23}'; -- thai character ro rua
	['\xc4'] = '\u{e24}'; -- thai character ru
	['\xc5'] = '\u{e25}'; -- thai character lo ling
	['\xc6'] = '\u{e26}'; -- thai character lu
	['\xc7'] = '\u{e27}'; -- thai character wo waen
	['\xc8'] = '\u{e28}'; -- thai character so sala
	['\xc9'] = '\u{e29}'; -- thai character so rusi
	['\xca'] = '\u{e2a}'; -- thai character so sua
	['\xcb'] = '\u{e2b}'; -- thai character ho hip
	['\xcc'] = '\u{e2c}'; -- thai character lo chula
	['\xcd'] = '\u{e2d}'; -- thai character o ang
	['\xce'] = '\u{e2e}'; -- thai character ho nokhuk
	['\xcf'] = '\u{e2f}'; -- thai character paiyannoi
	['\xd0'] = '\u{e30}'; -- thai character sara a
	['\xd1'] = '\u{e31}'; -- thai character mai han-akat
	['\xd2'] = '\u{e32}'; -- thai character sara aa
	['\xd3'] = '\u{e33}'; -- thai character sara am
	['\xd4'] = '\u{e34}'; -- thai character sara i
	['\xd5'] = '\u{e35}'; -- thai character sara ii
	['\xd6'] = '\u{e36}'; -- thai character sara ue
	['\xd7'] = '\u{e37}'; -- thai character sara uee
	['\xd8'] = '\u{e38}'; -- thai character sara u
	['\xd9'] = '\u{e39}'; -- thai character sara uu
	['\xda'] = '\u{e3a}'; -- thai character phinthu
	['\xdb'] = require 'parse.substitution.undefined_char';
	['\xdc'] = require 'parse.substitution.undefined_char';
	['\xdd'] = require 'parse.substitution.undefined_char';
	['\xde'] = require 'parse.substitution.undefined_char';
	['\xdf'] = '\u{e3f}'; -- thai currency symbol baht
	['\xe0'] = '\u{e40}'; -- thai character sara e
	['\xe1'] = '\u{e41}'; -- thai character sara ae
	['\xe2'] = '\u{e42}'; -- thai character sara o
	['\xe3'] = '\u{e43}'; -- thai character sara ai maimuan
	['\xe4'] = '\u{e44}'; -- thai character sara ai maimalai
	['\xe5'] = '\u{e45}'; -- thai character lakkhangyao
	['\xe6'] = '\u{e46}'; -- thai character maiyamok
	['\xe7'] = '\u{e47}'; -- thai character maitaikhu
	['\xe8'] = '\u{e48}'; -- thai character mai ek
	['\xe9'] = '\u{e49}'; -- thai character mai tho
	['\xea'] = '\u{e4a}'; -- thai character mai tri
	['\xeb'] = '\u{e4b}'; -- thai character mai chattawa
	['\xec'] = '\u{e4c}'; -- thai character thanthakhat
	['\xed'] = '\u{e4d}'; -- thai character nikhahit
	['\xee'] = '\u{e4e}'; -- thai character yamakkan
	['\xef'] = '\u{e4f}'; -- thai character fongman
	['\xf0'] = '\u{e50}'; -- thai digit zero
	['\xf1'] = '\u{e51}'; -- thai digit one
	['\xf2'] = '\u{e52}'; -- thai digit two
	['\xf3'] = '\u{e53}'; -- thai digit three
	['\xf4'] = '\u{e54}'; -- thai digit four
	['\xf5'] = '\u{e55}'; -- thai digit five
	['\xf6'] = '\u{e56}'; -- thai digit six
	['\xf7'] = '\u{e57}'; -- thai digit seven
	['\xf8'] = '\u{e58}'; -- thai digit eight
	['\xf9'] = '\u{e59}'; -- thai digit nine
	['\xfa'] = '\u{e5a}'; -- thai character angkhankhu
	['\xfb'] = '\u{e5b}'; -- thai character khomut
	['\xfc'] = require 'parse.substitution.undefined_char';
	['\xfd'] = require 'parse.substitution.undefined_char';
	['\xfe'] = require 'parse.substitution.undefined_char';
	['\xff'] = require 'parse.substitution.undefined_char';
}
