
local byte = require 'parse.substitution.charset.byte'

return byte + {
	['\xa1'] = require 'parse.substitution.undefined_char';
	['\xaa'] = '\u{d7}'; -- multiplication sign
	['\xba'] = '\u{f7}'; -- division sign
	['\xbf'] = require 'parse.substitution.undefined_char';
	['\xc0'] = require 'parse.substitution.undefined_char';
	['\xc1'] = require 'parse.substitution.undefined_char';
	['\xc2'] = require 'parse.substitution.undefined_char';
	['\xc3'] = require 'parse.substitution.undefined_char';
	['\xc4'] = require 'parse.substitution.undefined_char';
	['\xc5'] = require 'parse.substitution.undefined_char';
	['\xc6'] = require 'parse.substitution.undefined_char';
	['\xc7'] = require 'parse.substitution.undefined_char';
	['\xc8'] = require 'parse.substitution.undefined_char';
	['\xc9'] = require 'parse.substitution.undefined_char';
	['\xca'] = require 'parse.substitution.undefined_char';
	['\xcb'] = require 'parse.substitution.undefined_char';
	['\xcc'] = require 'parse.substitution.undefined_char';
	['\xcd'] = require 'parse.substitution.undefined_char';
	['\xce'] = require 'parse.substitution.undefined_char';
	['\xcf'] = require 'parse.substitution.undefined_char';
	['\xd0'] = require 'parse.substitution.undefined_char';
	['\xd1'] = require 'parse.substitution.undefined_char';
	['\xd2'] = require 'parse.substitution.undefined_char';
	['\xd3'] = require 'parse.substitution.undefined_char';
	['\xd4'] = require 'parse.substitution.undefined_char';
	['\xd5'] = require 'parse.substitution.undefined_char';
	['\xd6'] = require 'parse.substitution.undefined_char';
	['\xd7'] = require 'parse.substitution.undefined_char';
	['\xd8'] = require 'parse.substitution.undefined_char';
	['\xd9'] = require 'parse.substitution.undefined_char';
	['\xda'] = require 'parse.substitution.undefined_char';
	['\xdb'] = require 'parse.substitution.undefined_char';
	['\xdc'] = require 'parse.substitution.undefined_char';
	['\xdd'] = require 'parse.substitution.undefined_char';
	['\xde'] = require 'parse.substitution.undefined_char';
	['\xdf'] = '\u{2017}'; -- double low line
	['\xe0'] = '\u{5d0}'; -- hebrew letter alef
	['\xe1'] = '\u{5d1}'; -- hebrew letter bet
	['\xe2'] = '\u{5d2}'; -- hebrew letter gimel
	['\xe3'] = '\u{5d3}'; -- hebrew letter dalet
	['\xe4'] = '\u{5d4}'; -- hebrew letter he
	['\xe5'] = '\u{5d5}'; -- hebrew letter vav
	['\xe6'] = '\u{5d6}'; -- hebrew letter zayin
	['\xe7'] = '\u{5d7}'; -- hebrew letter het
	['\xe8'] = '\u{5d8}'; -- hebrew letter tet
	['\xe9'] = '\u{5d9}'; -- hebrew letter yod
	['\xea'] = '\u{5da}'; -- hebrew letter final kaf
	['\xeb'] = '\u{5db}'; -- hebrew letter kaf
	['\xec'] = '\u{5dc}'; -- hebrew letter lamed
	['\xed'] = '\u{5dd}'; -- hebrew letter final mem
	['\xee'] = '\u{5de}'; -- hebrew letter mem
	['\xef'] = '\u{5df}'; -- hebrew letter final nun
	['\xf0'] = '\u{5e0}'; -- hebrew letter nun
	['\xf1'] = '\u{5e1}'; -- hebrew letter samekh
	['\xf2'] = '\u{5e2}'; -- hebrew letter ayin
	['\xf3'] = '\u{5e3}'; -- hebrew letter final pe
	['\xf4'] = '\u{5e4}'; -- hebrew letter pe
	['\xf5'] = '\u{5e5}'; -- hebrew letter final tsadi
	['\xf6'] = '\u{5e6}'; -- hebrew letter tsadi
	['\xf7'] = '\u{5e7}'; -- hebrew letter qof
	['\xf8'] = '\u{5e8}'; -- hebrew letter resh
	['\xf9'] = '\u{5e9}'; -- hebrew letter shin
	['\xfa'] = '\u{5ea}'; -- hebrew letter tav
	['\xfb'] = require 'parse.substitution.undefined_char';
	['\xfc'] = require 'parse.substitution.undefined_char';
	['\xfd'] = '\u{200e}'; -- left-to-right mark
	['\xfe'] = '\u{200f}'; -- right-to-left mark
	['\xff'] = require 'parse.substitution.undefined_char';
}
