return require 'parse.char.utf8.set.Lowercase'
	+ require 'parse.char.utf8.set.Lt'
	+ require 'parse.char.utf8.set.Lm'
	+ require 'parse.char.utf8.set.Lo'
	+ require 'parse.char.utf8.set.Nl'
	+ require 'parse.char.utf8.set.Other_Alphabetic'
