return require 'parse.char.utf8.set.Word_Break.MidLetter'
	+ require 'parse.char.utf8.set.Word_Break.MidNumLet'
	+ require 'parse.char.utf8.set.Word_Break.Single_Quote'
	+ require 'parse.char.utf8.set.Mark.Nonspacing'
	+ require 'parse.char.utf8.set.Mark.Enclosing'
	+ require 'parse.char.utf8.set.Other.Format'
	+ require 'parse.char.utf8.set.Letter.Modifier'
	+ require 'parse.char.utf8.set.Symbol.Modifier'
