return require 'parse.char.utf8.set.ID_Start'
	+ require 'parse.char.utf8.set.Mark.Nonspacing'
	+ require 'parse.char.utf8.set.Mark.Spacing_Combining'
	+ require 'parse.char.utf8.set.Number.Decimal_Digit'
	+ require 'parse.char.utf8.set.Punctuation.Connector'
	+ require 'parse.char.utf8.set.Other_ID_Continue'
	- require 'parse.char.utf8.set.Pattern_Syntax'
	- require 'parse.char.utf8.set.Pattern_White_Space'
