return require 'parse.char.utf8.set.Pc'
	+ require 'parse.char.utf8.set.Pd'
	+ require 'parse.char.utf8.set.Ps'
	+ require 'parse.char.utf8.set.Pe'
	+ require 'parse.char.utf8.set.Pi'
	+ require 'parse.char.utf8.set.Pf'
	+ require 'parse.char.utf8.set.Po'
